"""
Export CLARA memories into the native auto-memory files. Stdlib-only (reuses
the fastpath's rank/format/sanitize helpers), so the daily maintenance pass
can call it without loading anything heavy.

Two targets per project:

- ``MEMORY.md`` — a marker-fenced section, budgeted to ≤ 60 lines / 6 KB so
  Claude's own notes keep most of the native 200-line/25 KB window.
- ``clara-memory.md`` — a fully CLARA-owned topic file with the whole
  active set (≤ 64 KB), grouped by type; native memory loads topic files
  on demand.

Every exported bullet carries ``<!--clara:<8-hex>-->`` provenance so the
importer can recognize CLARA's own lines anywhere.
"""

from __future__ import annotations

import os
import time
from datetime import datetime, timezone
from pathlib import Path

from clara.bridge import markers, paths
from clara.fastpath import context as fp_context
from clara.fastpath import db as fp_db

SECTION_MAX_LINES = 60
SECTION_MAX_BYTES = 6 * 1024
TOPIC_MAX_BYTES = 64 * 1024

_FORMATTERS = {
    "belief": fp_context._format_belief,
    "event": fp_context._format_event,
    "skill": fp_context._format_skill,
    "world_model": fp_context._format_world_model,
}
_GROUPS = [
    ("belief", "## Beliefs"),
    ("world_model", "## World model"),
    ("event", "## Events"),
    ("skill", "## Skills"),
]


def _provenance_tag(memory: dict[str, object]) -> str:
    memory_id = str(memory.get("memory_id", ""))
    return f" <!--clara:{memory_id[:8]}-->" if memory_id else ""


def _bullet(memory: dict[str, object]) -> str | None:
    formatter = _FORMATTERS.get(str(memory.get("type")))
    if formatter is None:
        return None
    try:
        return formatter(memory) + _provenance_tag(memory)
    except Exception:  # noqa: BLE001 — one bad row must not kill the export
        return None


def _excluded(memory: dict[str, object], target_name: str) -> bool:
    """Never echo a file's own imported lines back into it."""
    meta = memory.get("metadata")
    if not isinstance(meta, dict):
        return False
    origin = str(meta.get("origin_file", ""))
    return bool(origin) and origin.endswith(target_name)


_long = paths.long_path


def _atomic_write(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    _long(tmp).write_text(text, encoding="utf-8")
    os.replace(_long(tmp), _long(path))


def _read_if_exists(path: Path) -> str:
    lp = _long(path)
    return lp.read_text(encoding="utf-8") if lp.is_file() else ""


def build_section_body(memories: list[dict[str, object]], now_epoch: float) -> str:
    """The fenced MEMORY.md body: header note + top-ranked bullets in budget."""
    top = fp_context.rank(memories, now_epoch)
    lines = [
        "## CLARA memory (managed)",
        "Managed by the CLARA plugin - edit via memory tools "
        "(`memory_save`, `/clara:remember`); lines added below the fence "
        "are imported on the next sync. Full set: `clara-memory.md`.",
    ]
    for memory in top:
        bullet = _bullet(memory)
        if bullet is None:
            continue
        candidate = lines + [bullet]
        body = "\n".join(candidate) + "\n"
        if len(candidate) > SECTION_MAX_LINES or len(body.encode("utf-8")) > SECTION_MAX_BYTES:
            break
        lines = candidate
    return "\n".join(lines) + "\n"


def build_topic_file(memories: list[dict[str, object]], now_epoch: float) -> str:
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        "# CLARA memory (full set)",
        "",
        f"Generated by the CLARA plugin at {ts}. Do not edit — changes are "
        "overwritten on sync; use memory tools instead.",
        "",
    ]
    ranked = fp_context.rank(memories, now_epoch)
    ranked_ids = {str(m.get("memory_id")) for m in ranked}
    ordered = ranked + [m for m in memories if str(m.get("memory_id")) not in ranked_ids]
    for mem_type, header in _GROUPS:
        bucket = [m for m in ordered if m.get("type") == mem_type]
        if not bucket:
            continue
        lines.append(header)
        for memory in bucket:
            bullet = _bullet(memory)
            if bullet is None:
                continue
            candidate_text = "\n".join(lines + [bullet]) + "\n"
            if len(candidate_text.encode("utf-8")) > TOPIC_MAX_BYTES:
                lines.append(f"- … truncated at {TOPIC_MAX_BYTES // 1024} KB")
                return "\n".join(lines) + "\n"
            lines.append(bullet)
        lines.append("")
    return "\n".join(lines) + "\n"


def export_native(db_path: str, anchor: str | None = None) -> str:
    """Refresh MEMORY.md fence + topic file for *anchor*'s project.

    Returns a short human summary. Never raises on the normal disabled/no-op
    paths; unexpected errors propagate to the (fail-soft) caller.
    """
    anchor = anchor or os.getcwd()
    memory_md = paths.memory_md_path(anchor)
    topic = paths.topic_file_path(anchor)
    if memory_md is None or topic is None:
        return "auto-memory disabled"

    conn = fp_db.open_store(Path(db_path))
    if conn is None:
        return "store unreadable"
    try:
        memories = fp_db.fetch_active(conn)
    finally:
        conn.close()

    now_epoch = time.time()
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    from clara.store import resolve_store

    scope = resolve_store(anchor).scope

    section_memories = [m for m in memories if not _excluded(m, "MEMORY.md")]
    body = build_section_body(section_memories, now_epoch)

    _long(memory_md.parent).mkdir(parents=True, exist_ok=True)
    existing = _read_if_exists(memory_md)
    result = markers.replace_section(existing, body, store=scope, ts=ts)
    actions: list[str] = []
    if result.conflict_body is not None:
        actions.append("fence edited by hand — left in place (run `clara sync` to import it)")
    elif result.changed:
        _atomic_write(memory_md, result.text)
        actions.append("MEMORY.md updated")
    else:
        actions.append("MEMORY.md unchanged")

    topic_memories = [m for m in memories if not _excluded(m, paths.CLARA_TOPIC_FILE)]
    topic_text = build_topic_file(topic_memories, now_epoch)

    def _without_ts(text: str) -> str:
        return "\n".join(
            line for line in text.splitlines() if not line.startswith("Generated by")
        )

    existing_topic = _read_if_exists(topic)
    if _without_ts(existing_topic) != _without_ts(topic_text):
        _atomic_write(topic, topic_text)
        actions.append("topic file updated")
    return "; ".join(actions)
